# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf56e769cd3989f2e9865e3bbbf88d29b0209b411a688b85dabe8569d1275d909d46499ee5df576167f17eebb386c8653de6f305573d5f256385ad863ad78bba

test:
  secret_key_base: aad1ceac05b6f00c186f28c78f9db14845f6c47dd7515c11e29add501380a70ff1bdb983691435b4a871de95ab55472a31fa2e3659d86505583fdf0ce362a65e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
